# [cursor]
# style = "Beam"

[font]
size = 12.0

[font.normal]
family = "Monaspace Radon"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity=0.3

[window.padding]
x = 0
y = 0


[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

